# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PruebaDialog
                                 A QGIS plugin
 Este plugin se esta desarrollando como prueba del Plugin Builder
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-22
        git sha              : $Format:%H$
        copyright            : (C) 2024 by Cesar Vilca
        email                : vilcagamarracf@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'prueba_dialog_base.ui'))


class PruebaDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(PruebaDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        # Agregando conexiones
        self.pbCalcular.clicked.connect(self.onPbCalcularClicked)

    def onPbCalcularClicked(self):
        valor2 = self.spbCampo2.value()
        valor3 = self.spbCampo3.value()
        self.lblResultado.setText(f'{valor2*valor3}')
        